server:
  port: 9002
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring-cloud?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    show-sql: true
  #zipkin
  zipkin:
    base-url: http://127.0.0.1:9411/
  sleuth:
    sampler:
      probability: 1
#启用feign熔断      
feign:
  hystrix:
    enabled: true
#熔断超时
hystrix:
  command:
    default:
      execution:
        isolation:
          thread: 
            timeoutInMilliseconds: 500000
logging:
  level:
    org.springframework.cloud.openfeign: debug
girl:
  name: lucy
