server:
  port: 9001
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring-cloud?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    show-sql: true
  #zipkin
  zipkin:
    base-url: http://127.0.0.1:9411/
  sleuth:
    sampler:
      probability: 1
girl:
  name: lili
